[canary]
store = "./proofs"
key_file = "./public.pgp"
on_failure = ""

[logging]
file = "./log.txt"
level = "info"

[server]
port = 8080
timeout_read = 10
timeout_write = 10
enable_submit = true
enable_latest = true
enable_getkey = true
